controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_program_todo:
    path: /ProgramTodo/
    controller: App\Controller\LogController::index
